name: Test workflow

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello to the world
        id: helloworld
        run: |
          echo "Hello, World!"

      - name: Checkout repository
        uses: actions/checkout@v2.3.4

